sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-102.pdf --upload --lsstdoc DMTN-102.tex --env=travis --ltd-product dmtn-102"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "SqRJyTJ9llet7MHN64cQDpH3DZSZCWxZRi0cERiqP7z1DDOfBeFvcPuqy5l1nWzW4AlMIwiCpZQgzutZpftccYSTQR4NdRveEBmT3yge05uzTVX7aMd07VhyUz2ND4zF4ldhQzfDu92D9m5GuOF+yzbGWkhwf3N4kElhvJVzZxHr9SV+A1s7xOYKdk7cp5CnJbM91gtpZUblQjH2gAr4hMKxzPHmOFA1oDS2Ry6MHHX9PNt7Mny+t+C9zq6gQwYwLcmeIudB8Aue162R8Z/7kezQ7G/JKhuqljb2TzfTAv1k8x5sLb9qod3N/FBc78rLTJCFf37mCCzoq0xwTqZqsemjUHpbvv+Epp6hkmoZ9Fw5iD+DUP1mvH/2eV21IRmWPBYdwp78UvaQU3xQ/ime1voJR+SzyidoYbXmRF/8R615dpIt/JcMZXzX4Bi619Jt+DbOBxvHUwAhIWDN0xgyQD7t7gkgim4CHySz66gulIkUiNvCfLfYKgMZcDAZ8WppZlUCIVnw/9zOX982Ga+/LjyhAPtUAZN9C0Df8kOfYxQ73/Yg/iPs36SNeACMRfPZH9vweHdgF2boNUJIVOZvet0RhMXBYmnWYj0hR5fceTY7ZHvCRsud7DUaNAI/kYB8DNRhxn5+0bunIGpz/vvGg/5cVXQNZMcJ1ppn6HWkTYc="
    - secure: "I0V9bfVXqpnpdSDjhazsh1qJkjUovXNGfQTIHGVWe45BkXK14IYalW0Lso3RsVW9Rs250WYm0gOP0Q5R2jipjtj+zSq8VSarH4P4eW7RJybNEuVtA89Ih17qnP7WoYoSwORFbTdJpB/FTF2f0NEQBQ9WkaQRGPZS1UNL4o1YBUreKxyh5KHMGciJwkjz0uZwdm2WQLLsEXB9PykmtvgHukqgyqS+LR2eoZTi23WFmbk0208tD2iP3w1ZclQRfwZ7Jtn8SVK2xeq2jptxG64/S+Hcg5SAMlIZiiIEXz1110gKbKnP/XXwtrFTNx787ZPQYwo/e5BE1xOtlQRO3AtgChEZj0itdLK3+8Fj8veWaWkaoed0LIoMHce8vtTuwGUWE5v1wKIOfUJok4VPkPYdFvrBNfzJml5inlMWkzdpm3En5D0miJi8Otbb32saoaMBuSvMM3C9zbbanJY93mni7laeHrQ+/hVkO6f1fLnYXAx8e1XoltsAsiSRzpnx7I2tQKwIK4XnVuK/rptJLzlNPYRcb7rjjCZ98UfACAWMSH0GNR0Ttqq3agx8STydP4Ka7ighjOHi0/2UmXi/zsMFatw5/a3E/Zsp23sxk4bxc41AsFMvq2lCi1/s7D7C7yLyTnpSGjk5GvHoaEPplZ839hVKdCJdSnepnLcpibr9m8U="
